update build script to use changelog-derived version when building from an existing source tree
freedomofpress/securedrop-builder pull request #427
Opened 2023-03-14 14:58 UTC by zenmonkeykstop

Fixes #426 

Updates the build script as follows:
- when invoked without either PKG_PATH or PKG_VERSION set, will check out and verify latest prod tag and build package
- when invoked with PKG_VERSION, will check out and verify corresponding prod tag and build package
- when invoked with PKG_PATH, will use the source tree or tarball at `$PKG_PATH` to build package (no checkout, no tag verification)
- when invoked with PKG_GITREF, will check out corresponding gitref with no verification and build package 

In all cases the package version will be derived from the latest version in the source tree's `debian/changelog`, and if PKG_VERSION is specified and doesn't match the changelog, the build will not proceed.

## Testing:

- [ ] test building the current prod tag with `scripts/build-debianpackage securedrop-foo`
- [ ] test building an old prod tag with `PKG_VERSION=X.Y.Z scripts/build-debianpackage`
- [ ] test building an existing source tree with `PKG_PATH=../securedrop-foo scripts/build-debianpackage`

2023-03-14 21:06 UTC, legoktm commented
Nothing wrong with your code from a quick skim, but I'm not really sure we need to keep PKG_VERSION around? It currently does only two things 1) verify prod signed tag 2) print out what version we're using.

No. 2 is duplicative of dpkg-buildpackage's own message ("dpkg-buildpackage: info: source package securedrop-client
" & "dpkg-buildpackage: info: source version 0.9.0-rc2+bullseye").

So that just leaves No 1., verifying the prod signed tag. And I feel like there's a better way to do that... for example, we could run `git tag --points-at HEAD` and see whether it prints a `\d+?\.\d+?\.\d+?` matching string and if so, verify against the prod key.

2023-03-15 15:23 UTC, zenmonkeykstop commented
I'd go so far as to say (2) is actually misleading (hence the PR) - the package version is determined by the changelog, not by the tagged version that gets checked out. IMO we still have 3 basic cases to cover:
- like, build whatever source tree we get pointed at (wanna build a branch? nightlies? wanna build an rc? this is for you)
- check out an arbitrary ref and build it (wanna build as above without the hassle of prepping a source tree? et voila)
- check out a ref we expect to have a prod-signed tag and if so, build it (ok this is a serious build, let's be duly diligent)

But maybe what this actually points to is that we should be decomposing this script, doing the source tree prep and optional verification elsewhere if required, always just providing the prepped source tree, and focusing on the debian build bits.

2023-03-15 20:32 UTC, legoktm commented
> I'd go so far as to say (2) is actually misleading (hence the PR) - the package version is determined by the changelog, not by the tagged version that gets checked out. 

Agreed.

> IMO we still have 3 basic cases to cover:
> 
> * like, build whatever source tree we get pointed at (wanna build a branch? nightlies? wanna build an rc? this is for you)
> 
>  * check out an arbitrary ref and build it (wanna build as above without the hassle of prepping a source tree? et voila)
> 
>   * check out a ref we expect to have a prod-signed tag and if so, build it (ok this is a serious build, let's be duly diligent)

The third bullet is really just a special case of the second, no? In the MediaWiki release script that's basically how I treated it - accept any git ref, but if that ref is a tag, perform extra checks: https://gitlab.wikimedia.org/repos/releng/release/-/blob/f9857bd33d694aa6c492372f4111f599a3df6c87/make-release/makerelease2.py#L82

> But maybe what this actually points to is that we should be decomposing this script, doing the source tree prep and optional verification elsewhere if required, always just providing the prepped source tree, and focusing on the debian build bits.

"Yes, but..." I think that would be the ideal state to end up in, but I think we right now don't have a lot of confidence/trust in our builds yet because it is convoluted that I think having just one thing to run for now is better and once the whole process is simpler we can start breaking it down a bit.

2023-03-31 16:07 UTC, zenmonkeykstop commented
OK this is probably in better shape if @legoktm or anyone else has :eyes: time. PKG_VERSION dropped altogether, some hip-height guardrails added around production builds.

2023-03-31 19:38 UTC, legoktm requested changes
Minor thing, otherwise looks good. I do think we have officially reached the limits of what we can safely + easily do in bash scripting and any more complexity likely needs a Python port first.

2023-03-31 19:38 UTC, legoktm commented on scripts/build-debianpackage
> +            echo "PKG_PATH not set, using git reference $PKG_GITREF)..."
Unnecessary ) ?

2023-03-31 20:15 UTC, zenmonkeykstop commented
> Minor thing, otherwise looks good. I do think we have officially reached the limits of what we can safely + easily do in bash scripting and any more complexity likely needs a Python port first.

I'd agree with this assessment, was hard to resist the temptation.

2023-03-31 20:19 UTC, zenmonkeykstop commented on scripts/build-debianpackage
> +            echo "PKG_PATH not set, using git reference $PKG_GITREF)..."
Nuked!

2023-04-04 17:57 UTC, legoktm approved these changes
LGTM, test plan checks out. Docs PR is in progress, don't think we need to block on that.

2023-04-04 17:57 UTC, merged