Add Erik's pubkey
freedomofpress/securedrop-builder pull request #462
Opened 2023-09-09 00:15 UTC by eloquence

To update e.g. the bootstrap wheels, it'll be useful to have my pubkey among the ones that can sign sha256sums.

2023-09-12 15:56 UTC, legoktm requested changes
This file contains the key you've revoked (`1ED51D1B5D5A720738C5D161AA4BBAF2D8271BC4`) in addition to the key I assume you're intending to add (`E1F34FEAC85D9788C67555F1348F028C7FCB2899`).

I'm not sure how you exported it, but https://github.com/eloquence.gpg just has your new key in it, so committing that should be fine.

```
$ /usr/bin/gpg --import pubkeys/erik.pub 
gpg: key AA4BBAF2D8271BC4: public key "Erik Moeller <erik@freedom.press>" imported
gpg: key 348F028C7FCB2899: public key "Erik Moeller <erik@freedom.press>" imported
gpg: Total number processed: 2
gpg:               imported: 2
$ /usr/bin/gpg --list-keys erik@
pub   rsa4096 2018-02-07 [SC] [revoked: 2018-02-26]
      1ED51D1B5D5A720738C5D161AA4BBAF2D8271BC4
uid           [ revoked] Erik Moeller <erik@freedom.press>

pub   rsa4096 2018-02-26 [SC] [expires: 2024-02-25]
      E1F34FEAC85D9788C67555F1348F028C7FCB2899
uid           [ unknown] Erik Moeller <erik@freedom.press>
uid           [ unknown] Erik Moeller <eloquence@gmail.com>
sub   rsa4096 2021-02-25 [S] [expires: 2024-02-25]
sub   rsa4096 2021-02-25 [E] [expires: 2024-02-25]
sub   rsa4096 2021-02-25 [A] [expires: 2024-02-25]
```

2023-09-12 16:32 UTC, eloquence commented
Ah, exported via UID not fingerprint. Fixed!

2023-09-21 16:24 UTC, legoktm commented
LGTM, I'm going to squash this so that your revoked key doesn't end up in the git history

2023-09-21 16:26 UTC, legoktm approved these changes

2023-09-21 16:59 UTC, merged